# Generated by Django 5.2.1 on 2025-05-21 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reestr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin_bin', models.CharField(max_length=12, verbose_name='ИИН/БИН')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Наименование заказчика')),
                ('payer', models.CharField(max_length=255, verbose_name='Плательщик')),
                ('object_name', models.CharField(max_length=255, verbose_name='Наименование объекта оценки')),
                ('object_address', models.CharField(max_length=255, verbose_name='Адрес объекта оценки')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='№ Договора')),
                ('contract_date', models.DateField(verbose_name='Дата договора')),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма по договору')),
                ('actual_payment', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Фактическая оплата')),
                ('payment_status', models.CharField(max_length=100, verbose_name='Статус оплаты')),
                ('evaluation_count', models.PositiveIntegerField(verbose_name='Кол-во оценок')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Наименование Банка')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь кв.м.')),
                ('cost_per_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Стоимость за кв.м.')),
                ('title_number', models.CharField(max_length=100, verbose_name='Номер титулки')),
                ('is_offsite', models.CharField(max_length=100, verbose_name='Выездной')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время внесения')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Статус оплаты')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.department', verbose_name='Филиал')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name_plural': 'Реестр',
            },
        ),
    ]
