# Generated by Django 5.2.1 on 2025-06-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reestr',
            name='payment_status',
        ),
    ]
