# Generated by Django 5.2.1 on 2025-06-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_viewer',
            field=models.BooleanField(default=False),
        ),
    ]
